import type {
  AgentEdge,
  AgentNode,
  BuildPhase,
  ChatMessage,
  CodeFile,
  FrameworkId,
  KnowledgeFile,
  TraceEvent,
} from "./types";

function slugify(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 48);
}

function titleFromPrompt(prompt: string) {
  const cleaned = prompt.trim().replace(/^(build|create|make)\s+/i, "");
  const words = cleaned.split(/\s+/).slice(0, 5).join(" ");
  if (!words) return "Untitled App";
  return words.replace(/\b\w/g, (c) => c.toUpperCase());
}

function detectTemplate(prompt: string) {
  const p = prompt.toLowerCase();
  if (/sdr|sales|outreach|lead/.test(p)) return "sdr";
  if (/support|ticket|triage|helpdesk/.test(p)) return "support";
  if (/policy|legal|compliance|pdf|document/.test(p)) return "policy";
  if (/research|brief|report|analyst/.test(p)) return "research";
  if (/hr|resume|recruit|hiring/.test(p)) return "hr";
  return "generic";
}

export function buildAgents(seed: string, prompt: string): {
  agents: AgentNode[];
  edges: AgentEdge[];
} {
  const template = detectTemplate(prompt);
  const specs: Array<Omit<AgentNode, "id" | "x" | "y" | "status">> = [
    {
      name: "Router",
      role: "Classifies intent and routes work to specialists",
      model: "gpt-4.1",
      tools: ["classify", "memory"],
    },
    {
      name: template === "sdr" ? "Account Researcher" : "Researcher",
      role:
        template === "policy"
          ? "Retrieves and cites grounded document chunks"
          : "Gathers context from knowledge, tools, and the web",
      model: "claude-sonnet",
      tools: template === "policy" ? ["rag", "citations"] : ["rag", "web", "sql"],
    },
    {
      name: template === "support" ? "Triage Analyst" : "Analyst",
      role:
        template === "support"
          ? "Scores urgency and chooses a resolution path"
          : "Synthesizes findings into decisions and scores",
      model: "gpt-4.1",
      tools: ["rules", "scoring"],
    },
    {
      name: "Presenter",
      role: "Formats outputs into the product UI",
      model: "gemini-2.0",
      tools: ["markdown", "templates"],
    },
  ];

  const positions = [
    { x: 16, y: 42 },
    { x: 46, y: 20 },
    { x: 46, y: 64 },
    { x: 78, y: 42 },
  ];

  const agents: AgentNode[] = specs.map((spec, i) => ({
    id: `${seed}_a${i}`,
    ...spec,
    status: "ready",
    ...positions[i],
  }));

  const edges: AgentEdge[] = [
    { id: `${seed}_e1`, from: agents[0].id, to: agents[1].id, label: "needs facts" },
    { id: `${seed}_e2`, from: agents[0].id, to: agents[2].id, label: "needs judgment" },
    { id: `${seed}_e3`, from: agents[1].id, to: agents[3].id, label: "evidence" },
    { id: `${seed}_e4`, from: agents[2].id, to: agents[3].id, label: "decision" },
  ];

  return { agents, edges };
}

export function buildFiles(
  name: string,
  prompt: string,
  framework: FrameworkId,
  agents: AgentNode[],
): CodeFile[] {
  const slug = slugify(name) || "app";
  return [
    {
      path: "README.md",
      language: "markdown",
      content: `# ${name}\n\n${prompt}\n\nFramework: **${framework}**\n\nGenerated by Architect 2.0.\n`,
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `export default function Page() {\n  return (\n    <main className="min-h-screen bg-slate-950 text-slate-50 p-8">\n      <h1 className="text-3xl font-semibold">${name}</h1>\n      <p className="mt-2 text-slate-400">${prompt.replace(/`/g, "'").slice(0, 180)}</p>\n    </main>\n  );\n}\n`,
    },
    {
      path: "agents/graph.ts",
      language: "typescript",
      content: `export const graph = {\n  framework: "${framework}",\n  nodes: ${JSON.stringify(
        agents.map((a) => a.name),
        null,
        2,
      )},\n};\n`,
    },
    {
      path: "agents/router.py",
      language: "python",
      content: `class Router:\n    def run(self, message: str) -> dict:\n        return {"route": "research" if "why" in message.lower() else "analyze", "message": message}\n`,
    },
    {
      path: "package.json",
      language: "json",
      content: `{\n  "name": "${slug}",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build",\n    "start": "next start"\n  }\n}\n`,
    },
  ];
}

export function buildPreviewHtml(options: {
  name: string;
  prompt: string;
  agents: AgentNode[];
  knowledge?: KnowledgeFile[];
  accent?: string;
}) {
  const { name, prompt, agents, knowledge = [] } = options;
  const template = detectTemplate(prompt);
  const cards =
    template === "sdr"
      ? [
          ["Account brief", "Firmographics, triggers, and likely pains"],
          ["Outreach draft", "Personalized first-touch email"],
          ["Next steps", "Suggested sequence for the SDR"],
        ]
      : template === "support"
        ? [
            ["Ticket triage", "Priority, category, and owner"],
            ["Draft reply", "Customer-ready response"],
            ["Escalation", "When to route to a human"],
          ]
        : template === "policy"
          ? [
              ["Answer", "Grounded response with citations"],
              ["Sources", "Document chunks used"],
              ["Confidence", "Escalation threshold"],
            ]
          : [
              ["Research", "Collected evidence"],
              ["Analysis", "Key judgment calls"],
              ["Deliverable", "Shareable output"],
            ];

  const agentChips = agents
    .map(
      (a) =>
        `<span class="chip">${a.name}</span>`,
    )
    .join("");

  const knowledgeList = knowledge.length
    ? knowledge
        .map((k) => `<li><strong>${escapeHtml(k.name)}</strong> · ${k.content.length} chars</li>`)
        .join("")
    : "<li>No knowledge attached yet</li>";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(name)}</title>
<style>
  :root { color-scheme: dark; --bg:#070b12; --panel:#101826; --line:#24344c; --text:#e8eef7; --muted:#8fa3bd; --mint:#2dd4bf; --cyan:#38bdf8; }
  * { box-sizing: border-box; }
  body { margin:0; font-family: Manrope, Segoe UI, system-ui, sans-serif; background: radial-gradient(1000px 500px at 10% -10%, #16324f, var(--bg) 55%); color: var(--text); min-height:100vh; }
  header { display:flex; justify-content:space-between; align-items:center; gap:12px; padding:16px 20px; border-bottom:1px solid var(--line); background:rgba(7,11,18,.75); position:sticky; top:0; backdrop-filter: blur(8px); }
  .logo { font-weight:800; letter-spacing:-.02em; }
  .badge { font-size:12px; padding:6px 10px; border-radius:999px; background:#12352f; color:var(--mint); border:1px solid #1f6b5f; }
  main { padding:22px; display:grid; gap:16px; max-width:980px; margin:0 auto; }
  .hero, .card, .panel { border:1px solid var(--line); border-radius:16px; background:linear-gradient(160deg, rgba(45,212,191,.08), transparent 45%), var(--panel); }
  .hero { padding:22px; }
  h1 { margin:0 0 8px; font-size:28px; }
  p { margin:0; color:var(--muted); line-height:1.55; }
  .row { display:flex; flex-wrap:wrap; gap:8px; margin-top:14px; }
  button { border:0; border-radius:10px; padding:10px 14px; font-weight:700; cursor:pointer; }
  .primary { background:var(--mint); color:#042f2e; }
  .ghost { background:transparent; color:var(--text); border:1px solid var(--line); }
  .grid { display:grid; grid-template-columns:repeat(3,1fr); gap:12px; }
  .card { padding:14px; }
  .card h3 { margin:0 0 6px; font-size:14px; }
  .card p { font-size:12px; }
  .chip { display:inline-flex; margin:2px; padding:4px 8px; border-radius:999px; border:1px solid var(--line); background:#0c1320; font-size:11px; color:var(--cyan); }
  .panel { padding:14px; }
  input, textarea { width:100%; border-radius:12px; border:1px solid var(--line); background:#0c1320; color:var(--text); padding:10px 12px; font:inherit; }
  textarea { min-height:88px; resize:vertical; }
  .out { margin-top:12px; white-space:pre-wrap; font-size:13px; line-height:1.5; color:var(--text); }
  ul { margin:8px 0 0; padding-left:18px; color:var(--muted); font-size:13px; }
  @media (max-width:800px){ .grid{grid-template-columns:1fr;} }
</style>
</head>
<body>
  <header>
    <div class="logo">${escapeHtml(name)}</div>
    <div class="badge">Live agentic preview</div>
  </header>
  <main>
    <section class="hero">
      <h1>${escapeHtml(name)}</h1>
      <p>${escapeHtml(prompt)}</p>
      <div class="row">${agentChips}</div>
    </section>
    <section class="grid">
      ${cards
        .map(
          ([t, d]) =>
            `<article class="card"><h3>${t}</h3><p>${d}</p></article>`,
        )
        .join("")}
    </section>
    <section class="panel">
      <h3 style="margin:0 0 8px;font-size:14px;">Run a workflow</h3>
      <textarea id="q" placeholder="Ask the agents something…"></textarea>
      <div class="row">
        <button class="primary" id="run">Run agents</button>
        <button class="ghost" id="clear">Clear</button>
      </div>
      <div class="out" id="out">Ready. Enter a request and run the multi-agent workflow.</div>
    </section>
    <section class="panel">
      <h3 style="margin:0 0 4px;font-size:14px;">Knowledge</h3>
      <ul>${knowledgeList}</ul>
    </section>
  </main>
<script>
  const agents = ${JSON.stringify(agents.map((a) => ({ name: a.name, role: a.role })))};
  const knowledge = ${JSON.stringify(knowledge.map((k) => ({ name: k.name, content: k.content.slice(0, 1200) })))};
  const out = document.getElementById('out');
  document.getElementById('run').onclick = () => {
    const q = document.getElementById('q').value.trim() || 'Summarize the opportunity';
    const hits = knowledge.filter(k => k.content.toLowerCase().includes(q.toLowerCase().slice(0,12)) || q.length < 8).slice(0,2);
    const lines = [
      'Router → classified as ${template}',
      agents.map(a => a.name + ': ' + a.role).join('\\n'),
      hits.length ? ('Knowledge hits:\\n- ' + hits.map(h => h.name).join('\\n- ')) : 'Knowledge: no direct hit (using general reasoning)',
      '',
      'Presenter output:',
      '• Request: ' + q,
      '• Recommendation: proceed with the ${template} workflow',
      '• Confidence: 0.' + String(70 + (q.length % 20))
    ];
    out.textContent = lines.join('\\n');
  };
  document.getElementById('clear').onclick = () => { document.getElementById('q').value=''; out.textContent='Cleared.'; };
</script>
</body>
</html>`;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function applyChatEdit(
  html: string,
  instruction: string,
  name: string,
): string {
  const lower = instruction.toLowerCase();
  let next = html;
  if (/calm|softer|quiet|minimal/.test(lower)) {
    next = next.replace(/#2dd4bf/g, "#7dd3fc").replace(/#12352f/g, "#0c4a6e");
  }
  if (/darker|denser|compact/.test(lower)) {
    next = next.replace("padding:22px", "padding:14px");
  }
  if (/title|rename|call it|named/.test(lower)) {
    const match = instruction.match(/(?:title|rename|call it|named)\s+[\"']?([^\"'\n.]+)[\"']?/i);
    if (match?.[1]) {
      const newName = match[1].trim();
      next = next.replace(new RegExp(escapeRegExp(name), "g"), escapeHtml(newName));
    }
  }
  if (/citation|source/.test(lower) && !next.includes("Citations panel")) {
    next = next.replace(
      "</main>",
      `<section class="panel"><h3 style="margin:0 0 4px;font-size:14px;">Citations panel</h3><p>Sources will appear here after each run.</p></section></main>`,
    );
  }
  if (/button|cta|add a/.test(lower) && !next.includes("Secondary action")) {
    next = next.replace(
      '<button class="ghost" id="clear">Clear</button>',
      '<button class="ghost" id="clear">Clear</button><button class="ghost" id="secondary">Secondary action</button>',
    );
  }
  return next;
}

function escapeRegExp(s: string) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function buildTraces(agents: AgentNode[]): TraceEvent[] {
  const now = Date.now();
  return [
    {
      id: `t_${now}_1`,
      timestamp: now - 4000,
      agent: agents[0]?.name || "Router",
      event: "classified intent",
      status: "ok",
    },
    {
      id: `t_${now}_2`,
      timestamp: now - 3000,
      agent: agents[1]?.name || "Researcher",
      event: "retrieved knowledge context",
      status: "ok",
    },
    {
      id: `t_${now}_3`,
      timestamp: now - 2000,
      agent: agents[2]?.name || "Analyst",
      event: "produced decision score",
      status: "ok",
    },
    {
      id: `t_${now}_4`,
      timestamp: now - 1000,
      agent: "QA",
      event: "self-heal: fixed missing import",
      status: "heal",
    },
    {
      id: `t_${now}_5`,
      timestamp: now,
      agent: agents[3]?.name || "Presenter",
      event: "rendered UI surface",
      status: "ok",
    },
  ];
}

export type GenerationResult = {
  name: string;
  description: string;
  phase: BuildPhase;
  agents: AgentNode[];
  edges: AgentEdge[];
  files: CodeFile[];
  previewHtml: string;
  traces: TraceEvent[];
  messages: ChatMessage[];
};

export function generateProjectFromPrompt(input: {
  prompt: string;
  framework: FrameworkId;
  seed: string;
  knowledge?: KnowledgeFile[];
}): GenerationResult {
  const name = titleFromPrompt(input.prompt);
  const { agents, edges } = buildAgents(input.seed, input.prompt);
  const files = buildFiles(name, input.prompt, input.framework, agents);
  const previewHtml = buildPreviewHtml({
    name,
    prompt: input.prompt,
    agents,
    knowledge: input.knowledge,
  });
  const traces = buildTraces(agents);
  const now = Date.now();
  return {
    name,
    description: input.prompt.slice(0, 160),
    phase: "ready",
    agents,
    edges,
    files,
    previewHtml,
    traces,
    messages: [
      {
        id: `msg_${now}_u`,
        role: "user",
        content: input.prompt,
        timestamp: now - 1000,
      },
      {
        id: `msg_${now}_a`,
        role: "architect",
        content: `Built “${name}” with a ${agents.length}-agent graph on ${input.framework}. Preview is interactive — run a workflow inside the live app.`,
        timestamp: now,
        meta: "Plan → Agents → UI → QA",
      },
    ],
  };
}

export async function maybeEnhanceWithOpenAI(prompt: string, draftHtml: string) {
  const key = process.env.OPENAI_API_KEY;
  if (!key) return draftHtml;
  try {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        temperature: 0.4,
        messages: [
          {
            role: "system",
            content:
              "You improve HTML for an agentic app preview. Return ONLY a full HTML document. Keep it self-contained with inline CSS/JS. No markdown.",
          },
          {
            role: "user",
            content: `App prompt:\n${prompt}\n\nCurrent HTML:\n${draftHtml.slice(0, 12000)}\n\nImprove visual polish and keep the Run agents interaction.`,
          },
        ],
      }),
    });
    if (!res.ok) return draftHtml;
    const data = await res.json();
    const content = data.choices?.[0]?.message?.content?.trim();
    if (content?.includes("<html")) return content.replace(/^```html\n?|\n?```$/g, "");
    return draftHtml;
  } catch {
    return draftHtml;
  }
}
