import type { AgentEdge, AgentNode, CodeFile, Project } from "./types";
import { uid } from "./utils";

export function sampleAgents(seed: string): AgentNode[] {
  return [
    {
      id: `${seed}_router`,
      name: "Router",
      role: "Routes user intent to the right specialist",
      model: "gpt-4.1",
      tools: ["classify", "memory"],
      status: "ready",
      x: 18,
      y: 42,
    },
    {
      id: `${seed}_researcher`,
      name: "Researcher",
      role: "Pulls context from knowledge + tools",
      model: "claude-sonnet",
      tools: ["rag", "web", "sql"],
      status: "ready",
      x: 48,
      y: 22,
    },
    {
      id: `${seed}_analyst`,
      name: "Analyst",
      role: "Synthesizes findings into decisions",
      model: "gpt-4.1",
      tools: ["calc", "charts"],
      status: "ready",
      x: 48,
      y: 62,
    },
    {
      id: `${seed}_writer`,
      name: "Presenter",
      role: "Formats output for the product UI",
      model: "gemini-2.0",
      tools: ["markdown", "templates"],
      status: "ready",
      x: 78,
      y: 42,
    },
  ];
}

export function sampleEdges(seed: string): AgentEdge[] {
  return [
    { id: `${seed}_e1`, from: `${seed}_router`, to: `${seed}_researcher`, label: "needs facts" },
    { id: `${seed}_e2`, from: `${seed}_router`, to: `${seed}_analyst`, label: "needs judgment" },
    { id: `${seed}_e3`, from: `${seed}_researcher`, to: `${seed}_writer`, label: "evidence" },
    { id: `${seed}_e4`, from: `${seed}_analyst`, to: `${seed}_writer`, label: "decision" },
  ];
}

export function sampleFiles(name: string, framework: string): CodeFile[] {
  const slug = name.toLowerCase().replace(/\s+/g, "-");
  return [
    {
      path: "README.md",
      language: "markdown",
      content: `# ${name}\n\nGenerated by Architect 2.0 using **${framework}**.\n\n## Dual-lane project\n- Soft mode: prompt, preview, agent graph\n- Pro mode: source, terminal, PRs\n`,
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `export default function Page() {\n  return (\n    <main className="min-h-screen bg-slate-950 text-slate-50 p-8">\n      <h1 className="text-3xl font-semibold">${name}</h1>\n      <p className="mt-2 text-slate-400">Agentic workspace ready.</p>\n    </main>\n  );\n}\n`,
    },
    {
      path: "agents/graph.ts",
      language: "typescript",
      content: `import { createGraph } from "${framework}";\n\nexport const graph = createGraph({\n  name: "${slug}",\n  nodes: ["router", "researcher", "analyst", "presenter"],\n  edges: [\n    ["router", "researcher"],\n    ["router", "analyst"],\n    ["researcher", "presenter"],\n    ["analyst", "presenter"],\n  ],\n});\n`,
    },
    {
      path: "agents/researcher.py",
      language: "python",
      content: `class Researcher:\n    """Pulls grounded context for the app."""\n\n    def run(self, query: str, corpus: list[str]) -> dict:\n        return {"query": query, "hits": corpus[:3], "confidence": 0.91}\n`,
    },
    {
      path: "package.json",
      language: "json",
      content: `{\n  "name": "${slug}",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build"\n  }\n}\n`,
    },
  ];
}

export function previewMarkup(title: string, description: string) {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    :root { color-scheme: dark; }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: "Segoe UI", system-ui, sans-serif;
      background: radial-gradient(1200px 600px at 10% -10%, #16324f, #070b12 55%);
      color: #e8eef7;
      min-height: 100vh;
    }
    header {
      display: flex; justify-content: space-between; align-items: center;
      padding: 18px 24px; border-bottom: 1px solid #223247;
    }
    .logo { font-weight: 700; letter-spacing: 0.02em; }
    .chip {
      font-size: 12px; padding: 6px 10px; border-radius: 999px;
      background: #12352f; color: #5eead4; border: 1px solid #1f6b5f;
    }
    main { padding: 28px 24px; display: grid; gap: 16px; }
    .hero {
      padding: 24px; border: 1px solid #27405f; border-radius: 18px;
      background: linear-gradient(160deg, rgba(34,211,238,.08), transparent 50%), #0d1522;
    }
    h1 { margin: 0 0 8px; font-size: 28px; }
    p { margin: 0; color: #9fb0c7; line-height: 1.5; }
    .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }
    .card {
      padding: 16px; border-radius: 14px; border: 1px solid #24344c;
      background: #0c1320;
    }
    .card h3 { margin: 0 0 6px; font-size: 14px; }
    .card p { font-size: 12px; }
    .row { display: flex; gap: 8px; margin-top: 16px; }
    button {
      border: 0; border-radius: 10px; padding: 10px 14px; font-weight: 600; cursor: pointer;
    }
    .primary { background: #2dd4bf; color: #042f2e; }
    .ghost { background: transparent; color: #c9d7ea; border: 1px solid #314761; }
  </style>
</head>
<body>
  <header>
    <div class="logo">${title}</div>
    <div class="chip">Live preview · agentic</div>
  </header>
  <main>
    <section class="hero">
      <h1>${title}</h1>
      <p>${description || "Your agentic application is assembling in real time."}</p>
      <div class="row">
        <button class="primary">Run workflow</button>
        <button class="ghost">View agents</button>
      </div>
    </section>
    <section class="grid">
      <div class="card"><h3>Router</h3><p>Classifies intent and picks a path.</p></div>
      <div class="card"><h3>Research</h3><p>Grounds answers in your knowledge.</p></div>
      <div class="card"><h3>Presenter</h3><p>Renders decisions into the UI.</p></div>
    </section>
  </main>
</body>
</html>`;
}

export const PROMPT_STARTERS = [
  {
    title: "SDR research desk",
    prompt:
      "Build an agentic SDR desk that researches accounts, drafts personalized outreach, and logs next steps for sales.",
    tag: "Revenue",
  },
  {
    title: "Policy Q&A copilot",
    prompt:
      "Create an internal policy copilot that answers from uploaded PDFs, cites sources, and escalates uncertain answers.",
    tag: "Ops",
  },
  {
    title: "Support triage app",
    prompt:
      "Make a support triage app that classifies tickets, drafts replies, and routes critical issues to humans.",
    tag: "Support",
  },
  {
    title: "Research brief factory",
    prompt:
      "Build a research brief factory: one prompt in, multi-agent web research out, with charts and a shareable brief.",
    tag: "Research",
  },
];

export function seedDemoProject(userName: string): Project {
  const id = uid("proj");
  const name = "Account Research Desk";
  const prompt =
    "Build an agentic research desk that turns a company name into a brief with risks, opportunities, and outreach angles.";
  return {
    id,
    name,
    description: `Demo project for ${userName}`,
    prompt,
    framework: "lyzr",
    mode: "soft",
    phase: "ready",
    createdAt: Date.now() - 1000 * 60 * 60 * 26,
    updatedAt: Date.now() - 1000 * 60 * 18,
    githubConnected: true,
    githubRepo: "anuj/account-research-desk",
    deployed: true,
    deployUrl: "https://account-research.architect.new",
    agents: sampleAgents(id),
    edges: sampleEdges(id),
    messages: [
      {
        id: uid("msg"),
        role: "user",
        content: prompt,
        timestamp: Date.now() - 1000 * 60 * 40,
      },
      {
        id: uid("msg"),
        role: "architect",
        content:
          "Mapped a 4-agent graph (Router → Researcher/Analyst → Presenter), generated the UI, and self-healed two type errors. Soft mode stays conversational; switch to Pro anytime to edit source.",
        timestamp: Date.now() - 1000 * 60 * 38,
        meta: "Plan → Agents → UI → QA",
      },
    ],
    files: sampleFiles(name, "lyzr"),
    previewHtml: previewMarkup(name, prompt),
    knowledgeFiles: ["icp-guide.pdf", "competitor-notes.md"],
  };
}
